# Generated by Django 2.2 on 2020-04-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_details', models.TextField()),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Pending', 'Pending'), ('Re-Opened', 'Re-Opened')], default='Pending', max_length=30)),
                ('reopened_count', models.IntegerField(default=0)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('committee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Committees')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints_Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reopen_count', models.IntegerField()),
                ('action_report', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Complaints')),
                ('reacting_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Reopen_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reopen_count', models.IntegerField()),
                ('comments', models.TextField()),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.TextField()),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Complaints')),
            ],
        ),
    ]
