# Generated by Django 2.2 on 2020-04-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0002_complaint_reopen_comments_complaints_complaints_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_reopen_comments',
            name='revoked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='revoked_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
