# Generated by Django 2.2 on 2020-03-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0002_auto_20200324_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_subject',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
