# Generated by Django 2.2 on 2020-05-07 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0002_auto_20200507_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(max_length=100)),
                ('committee_details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_details', models.TextField()),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Pending', 'Pending'), ('Re-Opened', 'Re-Opened'), ('Revoked', 'Revoked')], default='Pending', max_length=30)),
                ('reopened_count', models.IntegerField(default=0)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.TextField(blank=True, null=True)),
                ('revoked_date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('committee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Committees')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('accronym', models.CharField(default=None, max_length=10)),
                ('is_mid_sem_live', models.BooleanField(default=True)),
                ('is_end_sem_live', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='End_Sem_Feedback_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('Q1', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q2', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q3', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q4', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q5', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q6', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q7', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q8', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q9', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q10', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('remarks', models.TextField(default=None, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Departments')),
            ],
            options={
                'get_latest_by': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='End_Sem_Feedback_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hod', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auth_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Mid_Sem_Feedback_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('Q1', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q2', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q3', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q4', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q5', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q6', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q7', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q8', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q9', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Q10', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('remarks', models.TextField(default=None, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Departments')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty')),
            ],
            options={
                'get_latest_by': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Mid_Sem_Feedback_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_code', models.CharField(max_length=10)),
                ('div', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_to_Faculty_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('enrollment_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('div', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auth_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentSupport.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Feedback_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_sem_feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.End_Sem_Feedback_Answers')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty')),
                ('mid_sem_feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Mid_Sem_Feedback_Answers')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('auth_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_subject', models.TextField()),
                ('news_details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('issuing_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty')),
                ('target_audience', models.ManyToManyField(to='StudentSupport.Departments')),
            ],
        ),
        migrations.AddField(
            model_name='mid_sem_feedback_answers',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Students'),
        ),
        migrations.AddField(
            model_name='mid_sem_feedback_answers',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Subjects'),
        ),
        migrations.AddField(
            model_name='end_sem_feedback_answers',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty'),
        ),
        migrations.AddField(
            model_name='end_sem_feedback_answers',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Students'),
        ),
        migrations.AddField(
            model_name='end_sem_feedback_answers',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Subjects'),
        ),
        migrations.CreateModel(
            name='Complaints_Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reopen_count', models.IntegerField(default=0)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Complaints')),
                ('reacting_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='complaints',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Students'),
        ),
        migrations.CreateModel(
            name='Complaint_Reopen_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reopen_count', models.IntegerField()),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Complaints')),
            ],
        ),
        migrations.AddField(
            model_name='committees',
            name='chairperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty'),
        ),
        migrations.CreateModel(
            name='Committee_to_Members_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('committee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Committees')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty')),
            ],
        ),
    ]
