# Generated by Django 2.2 on 2020-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0003_news_news_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='target_audience',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=9),
        ),
    ]
