# Generated by Django 2.2 on 2020-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0003_auto_20200429_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Pending', 'Pending'), ('Re-Opened', 'Re-Opened'), ('Revoked', 'Revoked')], default='Pending', max_length=30),
        ),
    ]
