# Generated by Django 2.2 on 2020-03-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0004_auto_20200324_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm',
        ),
    ]
