# Generated by Django 2.2 on 2020-04-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0004_auto_20200429_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints_solutions',
            name='reopen_count',
            field=models.IntegerField(default=0),
        ),
    ]
