# Generated by Django 2.2 on 2020-03-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0005_remove_user_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee_details',
            name='chairperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty'),
        ),
    ]
