# Generated by Django 2.2 on 2020-05-10 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0005_auto_20200510_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='auth_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
