# Generated by Django 2.2 on 2020-05-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0005_auto_20200430_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints_solutions',
            old_name='action_report',
            new_name='action',
        ),
    ]
