# Generated by Django 2.2 on 2020-03-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0006_auto_20200324_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='hod',
            field=models.BooleanField(default=False),
        ),
    ]
