# Generated by Django 2.2 on 2020-05-01 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0006_auto_20200501_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_reopen_comments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
