# Generated by Django 2.2 on 2020-05-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0007_complaint_reopen_comments_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_reopen_comments',
            name='revoked',
        ),
        migrations.RemoveField(
            model_name='complaint_reopen_comments',
            name='revoked_reason',
        ),
    ]
