# Generated by Django 2.2 on 2020-05-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0007_auto_20200510_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='accronym',
            field=models.CharField(default=None, max_length=10, verbose_name='Accronym'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='dept_name',
            field=models.CharField(max_length=100, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='is_end_sem_live',
            field=models.BooleanField(default=True, verbose_name='End Semester Feedback'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='is_mid_sem_live',
            field=models.BooleanField(default=True, verbose_name='Mid Semester Feedback'),
        ),
    ]
