# Generated by Django 2.2 on 2020-05-10 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0008_auto_20200510_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active/Retired'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='auth_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Departments', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='hod',
            field=models.BooleanField(default=False, verbose_name='HOD/Faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Faculty Name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registered Date'),
        ),
    ]
