# Generated by Django 2.2 on 2020-05-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0008_auto_20200502_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='revoked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
