# Generated by Django 2.2 on 2020-04-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0009_auto_20200407_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
