# Generated by Django 2.2 on 2020-05-10 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0009_auto_20200510_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='auth_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='auth_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='students',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Departments', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='students',
            name='div',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='students',
            name='enrollment_no',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Enrollment No'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='students',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Principal', 'Principal')], default='Student', max_length=20, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registered Dater'),
        ),
    ]
