# Generated by Django 2.2 on 2020-05-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0009_complaints_revoked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='div',
        ),
        migrations.AddField(
            model_name='departments',
            name='div',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
