# Generated by Django 2.2 on 2020-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0010_auto_20200504_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='div',
        ),
        migrations.AddField(
            model_name='students',
            name='div',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
