# Generated by Django 2.2 on 2020-04-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0011_auto_20200412_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_feedback_status',
            name='end_sem_is_given',
        ),
        migrations.RemoveField(
            model_name='student_feedback_status',
            name='is_given',
        ),
        migrations.AddField(
            model_name='student_feedback_status',
            name='end_sem_feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.End_Sem_Feedback_Answers'),
        ),
        migrations.AddField(
            model_name='student_feedback_status',
            name='mid_sem_feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Mid_Sem_Feedback_Answers'),
        ),
    ]
