# Generated by Django 2.2 on 2020-05-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0011_auto_20200510_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Principal', 'Principal')], default='Student', max_length=20, verbose_name='Role'),
        ),
    ]
