# Generated by Django 2.2 on 2020-05-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0012_auto_20200510_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Departments', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='div',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Removed or Not'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(max_length=10, verbose_name='Subject Code'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(max_length=255, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added Date'),
        ),
    ]
