# Generated by Django 2.2 on 2020-04-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0012_auto_20200415_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_feedback_status',
            name='faculty_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty'),
            preserve_default=False,
        ),
    ]
