# Generated by Django 2.2 on 2020-05-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0013_auto_20200510_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_to_faculty_mapping',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty', verbose_name='Teaching Faculty'),
        ),
        migrations.AlterField(
            model_name='subject_to_faculty_mapping',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Subjects', verbose_name='Subject'),
        ),
    ]
