# Generated by Django 2.2 on 2020-04-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0013_student_feedback_status_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='accronym',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(max_length=255),
        ),
    ]
