# Generated by Django 2.2 on 2020-05-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0014_auto_20200510_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='Q1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Question 1'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='Q10',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Question 10'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='Q2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Question 2'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='Q3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Question 3'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='Q4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Question 4'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='Q5',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Question 5'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='Q6',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Question 6'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='Q7',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Question 7'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='Q8',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Question 8'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='Q9',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Question 9'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Departments', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Consent'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='remarks',
            field=models.TextField(default=None, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Students', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Subjects', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
