# Generated by Django 2.2 on 2020-04-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0015_auto_20200416_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end_sem_feedback_answers',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mid_sem_feedback_answers',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='program_exit_survey_answers',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
