# Generated by Django 2.2 on 2020-05-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0017_auto_20200510_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_reopen_comments',
            name='comments',
            field=models.TextField(verbose_name='Reopen Comment'),
        ),
        migrations.AlterField(
            model_name='complaint_reopen_comments',
            name='complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Complaints', verbose_name='Complaint'),
        ),
        migrations.AlterField(
            model_name='complaint_reopen_comments',
            name='reopen_count',
            field=models.IntegerField(verbose_name='Reopen Count'),
        ),
        migrations.AlterField(
            model_name='complaint_reopen_comments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reopened Date'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='committee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Committees', verbose_name='Committee'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaint_details',
            field=models.TextField(verbose_name='Complaint'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='reopened_count',
            field=models.IntegerField(default=0, verbose_name='Reopened count'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='revoked',
            field=models.BooleanField(default=False, verbose_name='Is Revoked'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='revoked_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Revocation'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='revoked_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason of Revocation'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Pending', 'Pending'), ('Re-Opened', 'Re-Opened'), ('Revoked', 'Revoked')], default='Pending', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Students', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='complaints_solutions',
            name='action',
            field=models.TextField(verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='complaints_solutions',
            name='complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Complaints', verbose_name='Complaint'),
        ),
        migrations.AlterField(
            model_name='complaints_solutions',
            name='reacting_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty', verbose_name='Committee Member'),
        ),
        migrations.AlterField(
            model_name='complaints_solutions',
            name='reopen_count',
            field=models.IntegerField(default=0, verbose_name='Complaint Reopen Count'),
        ),
        migrations.AlterField(
            model_name='complaints_solutions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Action taken date'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='description',
            field=models.TextField(verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Issuer Email'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Issuer Name'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='issuing_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty', verbose_name='Author Faculty'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_details',
            field=models.TextField(verbose_name='News'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_subject',
            field=models.TextField(verbose_name='News Heading'),
        ),
        migrations.AlterField(
            model_name='news',
            name='target_audience',
            field=models.ManyToManyField(to='StudentSupport.Departments', verbose_name='Target Audience'),
        ),
        migrations.AlterField(
            model_name='news',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='student_feedback_status',
            name='end_sem_feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.End_Sem_Feedback_Answers', verbose_name='End Semester Feedback'),
        ),
        migrations.AlterField(
            model_name='student_feedback_status',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='student_feedback_status',
            name='mid_sem_feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Mid_Sem_Feedback_Answers', verbose_name='Mid Semester Feedback'),
        ),
        migrations.AlterField(
            model_name='student_feedback_status',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Students', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='student_feedback_status',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSupport.Subjects', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='student_feedback_status',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
    ]
