# Generated by Django 2.2 on 2020-04-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0017_auto_20200420_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='end_sem_feedback_answers',
            options={'get_latest_by': ['timestamp']},
        ),
    ]
