# Generated by Django 2.2 on 2020-05-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0018_auto_20200510_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee_to_members_mapping',
            options={'verbose_name': 'Committee to member mapping', 'verbose_name_plural': 'Committee to member mapping'},
        ),
        migrations.AlterModelOptions(
            name='committees',
            options={'verbose_name': 'Committee', 'verbose_name_plural': 'Committees'},
        ),
        migrations.AlterModelOptions(
            name='complaint_reopen_comments',
            options={'verbose_name': 'Reopen Comments of student complaints', 'verbose_name_plural': 'Reopen Comments of student complaints'},
        ),
        migrations.AlterModelOptions(
            name='complaints',
            options={'verbose_name': 'Student Complaints', 'verbose_name_plural': 'Student Complaints'},
        ),
        migrations.AlterModelOptions(
            name='complaints_solutions',
            options={'verbose_name': 'Solution of Student Complaints', 'verbose_name_plural': 'Solution of Student Complaints'},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Departments', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='end_sem_feedback_answers',
            options={'get_latest_by': ['timestamp'], 'verbose_name': 'End Semester Feedback', 'verbose_name_plural': 'End Semester Feedback'},
        ),
        migrations.AlterModelOptions(
            name='end_sem_feedback_questions',
            options={'verbose_name': 'End Semester Feedback Question', 'verbose_name_plural': 'End Semester Feedback Questions'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterModelOptions(
            name='mid_sem_feedback_answers',
            options={'get_latest_by': ['timestamp'], 'verbose_name': 'Mid Semester Feedback', 'verbose_name_plural': 'Mid Semester Feedback'},
        ),
        migrations.AlterModelOptions(
            name='mid_sem_feedback_questions',
            options={'verbose_name': 'Mid Semester Feedback Question', 'verbose_name_plural': 'Mid Semester Feedback Questions'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='student_feedback_status',
            options={'verbose_name': 'Feedback Status of Students', 'verbose_name_plural': 'Feedback Status of Students'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='subject_to_faculty_mapping',
            options={'verbose_name': 'Subject to Faculty Mapping', 'verbose_name_plural': 'Subject to Faculty Mapping'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
