# Generated by Django 2.2 on 2020-04-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0019_students_div'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='target_audience',
        ),
        migrations.AddField(
            model_name='news',
            name='target_audience',
            field=models.ManyToManyField(to='StudentSupport.Departments'),
        ),
    ]
