# Generated by Django 2.2 on 2020-04-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0020_auto_20200424_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
